# -*- coding: utf-8 -*-
{
    "name": "HRM API",
    "summary": "Mobile API for HRM",
    "description": """Mobile API for HRM""",
    "author": "Smarten Technologies Pvt. Ltd",
    "website": "https://www.smarten.com.np",
    "category": "Uncategorized",
    "version": "19.0.1.0.0",
    "depends": [
        "mobile_auth",
        "website",
        "hr",
        "hr_holidays",
        "web",
        "helpdesk",
        "project",
        "hr_payroll",
        "hr_attendance",
        "hr_expense",
        "approvals",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/approval_category_data.xml",
        "views/external_news.xml",
        "views/approval_category_views.xml",
        "views/employee_view.xml",
    ],
    "assets": {},
}
